apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-atvarsapinis
  labels:
    # Replace this by your own name
    createdBy: "Atvars-Apinis"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: atvarsap/bigdataai_exam:api
          env:
            - name: NAME
              value: atvars
            - name: DATE
              value: 08/05/2024

          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 80
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
         
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: exam-atvarsapinis
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-atvarsapinis
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3d-k3s-default-agent-2
      containers:
      - name: frontend
        image: atvarsap/bigdataai_exam:frontend

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-atvarsapinis
spec:
  
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    nodePort: 30000

