services:
  api:
    image: exam_api
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 8001:80
  frontend:
    image: exam_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      API_PORT: 80
      API_HOST: api
      NAME: "Nathan Segers"
