version: '3.9'

services:
  web:
    build:
      context: ./pointsApp
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - web
      - database
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pointsApp/templates/:/templates
  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U POSTGRES_USER -d POSTGRES_DB
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database
    volumes:
      - database:/var/lib/postgresql/data/

networks:
  web:
  database:

volumes:
  database: